#!/bin/bash
set -e

# source the foxy setup if it's their in case the user wants to start using
# it right away after install. The following 5 lines are also loaded into
# ~/.profile.d/ to get run normally too

FOXYFILE="/opt/ros/foxy/local_setup.bash"
OPEN_VINS="/opt/ros/foxy/open_vins/"
OPEN_VINS_FILE="${OPEN_VINS}/install/setup.bash"
if [ -f $FOXYFILE ]; then
	source $OPEN_VINS_FILE
fi

build_dir="/home/root"

find $OPEN_VINS -type l -exec bash -c '
    link_target=$(readlink "$1")
    if [ ! -e "$link_target" ]; then
		echo "TARGET: $link_target"
        if [[ "$link_target" == ${build_dir}/open_vins/colcon_ws/build/* ]]; then
            BUILD_PATH=$(echo "$link_target" | cut -d'/' -f 7-)
            correct_path="/opt/ros/foxy/open_vins/build/$BUILD_PATH"

            if [ -e "$correct_path" ]; then
                echo "Correcting symlink: $1 -> $correct_path"
                ln -sf "$correct_path" "$1"
            else
                echo "Error: Target file not found for $1"
            fi

         elif [[ "$link_target" == ${build_dir}/open_vins/colcon_ws/src/* ]]; then
            SRC_PATH=$(echo "$link_target" | cut -d'/' -f 7-)
            correct_path="/opt/ros/foxy/open_vins/src/$SRC_PATH"

            if [ -e "$correct_path" ]; then
                echo "Correcting symlink: $1 -> $correct_path"
                ln -sf "$correct_path" "$1"
            else
                echo "Error: Target file not found for $1"
            fi

        fi
    fi
' _ {} \;